var next = '&rarr;';
var prev = '&larr;';
var spaces = '&nbsp;&nbsp;&nbsp;&nbsp;';
var spaces2 = ' &nbsp; &nbsp; ';
var amp = '&amp;';
var iquest = '&iquest;'
var ae = '&AElig;'
var euml = '&euml;'
var hearts	= 'I &hearts; Prettier';
